---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - vault_install

- hosts: all
  vars:
    unseal_keys_dir_output: "{{ playbook_dir }}/unsealKey"
    root_token_dir_output: "{{ playbook_dir }}/rootKey"
  roles:
    - vault_init
    - vault_unseal
  
- hosts: all
  roles:
    - go_install

- hosts: all
  roles:
    - redis_plugin
  environment:
    REDIS_HOST: 20.120.42.38

