---
# tasks file for go_install
- name: Download go lang
  become: yes
  get_url:
    url: https://storage.googleapis.com/golang/go1.17.3.linux-amd64.tar.gz
    dest: /tmp/

- name: Extract go1.17.3.linux-amd64.tar.gz into /usr/local
  become: yes
  ansible.builtin.unarchive:
    remote_src: yes
    src: /tmp/go1.17.3.linux-amd64.tar.gz
    dest: /usr/local/
