name: Init Services

on: 
  push:
    branches: [ master ]
    paths: 
      - ".github/workflows/01_init_all.yml"
  pull_request:
    branches: [ master ]
    paths: 
      - ".github/workflows/01_init_all.yml"

jobs:

  adservice:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: "Login Azure ClI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}
        
    - name: 'Login Azure ACR'
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}
    
    - name: Build the Docker images
      run: |
           az acr build  --registry hipsterequipofive1 --image adservice:v1 src/adservice/.

