name: Init Services   

on: 
  push:
    branches: [ master ]
    paths: 
      - ".github/workflows/01_terraform_infra.yml" 
  pull_request:
    branches: [ master ]
    paths: 
      - ".github/workflows/01_terraform_infra.yml" 

jobs:
  terraform_infra:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      TF_VAR_SSH_KEY: ${{secrets.TF_VAR_SSH_KEY}}


    steps:
      - uses: actions/checkout@v2

      - name: "Login Azure ClI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PROJECTIN_SP }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd 01_Terraform_IaC
          terraform init

      - name: Terraform plan
        run: |
          cd 01_Terraform_IaC
          terraform plan

      - name: Terraform apply
        run: |
          cd 01_Terraform_IaC
          terraform apply --auto-approve

      - name: Terraform Format    
        run: |
          cd 01_Terraform_IaC
          terraform fmt -check 

      - name: Attach ACR to AKS    
        run: |
          az aks update -n aks-hipster-dev-eastus -g rg-hipster-dev-eastus --attach-acr hipsterequipofive1
