name: Init Services

on: 
  push:
    branches: [ master ]
    paths: 
      - ".github/workflows/02_helm_workflow.yml"
  pull_request:
    branches: [ master ]
    paths: 
      - ".github/workflows/02_helm_workflow.yml"

jobs:

  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: "Login Azure ClI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}

#    - name: "Secret Cluster"
#      uses: azure/k8s-create-secret@v1
#      with:
#        container-registry-url: ${{ secrets.ACR_SERVER }}
#        container-registry-username: 1ef4f5d5-503e-40e7-8559-eef6885af25b
#        container-registry-password: ALTV3y-_JeXZ1EthtztPpHK.wuyNA8PILK
#        secret-name: octapal
#        namespace: default
#        force: true

    - name: "Login AKS"
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }} # Azure credentials
        resource-group: 'hipster-rg'
        cluster-name: 'hipster-aks'
    id: login  
    
    - name: 'Install helm'
      uses: azure/setup-helm@v1
      with:
        version: latest # default is latest stable
      id: install

    - name: Helm list
      run: |
           helm list
