name: Init all Images 

on: 
  push:
    branches: [ master ] 
    paths: 
      - ".github/workflows/02_init_images.yml" 
  pull_request:
    branches: [ master ]
    paths: 
      - ".github/workflows/02_init_images.yml"

jobs:

  build_img:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: "Login Azure ClI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}
        
    - name: 'Login Azure ACR'
      uses: azure/docker-login@v1
      with:
          login-server: anthosequipofive1.azurecr.io
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}
    
    - name: Build the Docker accounts-db
      run: |
           docker build 02_Application/src/accounts-db/. --tag anthosequipofive1.azurecr.io/accounts-db:latest
           docker push anthosequipofive1.azurecr.io/accounts-db:latest


    - name: Build the Docker balancereader
      run: |
           docker pull gcr.io/bank-of-anthos/balancereader:latest
           docker tag gcr.io/bank-of-anthos/balancereader:latest anthosequipofive1.azurecr.io/balancereader:latest
           docker push anthosequipofive1.azurecr.io/balancereader:latest





    
