name: Init all Images 

on: 
  push:
    branches: [ master ] 
    paths: 
      - ".github/workflows/02_init_images.yml" 
  pull_request:
    branches: [ master ]
    paths: 
      - ".github/workflows/02_init_images.yml"

jobs:

  build_img:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: "Login Azure ClI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}
        
    - name: 'Login Azure ACR'
      uses: azure/docker-login@v1
      with:
          login-server: anthosequipofive1.azurecr.io
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}
    
    - name: Build the Docker accounts-db
      run: |
           docker build 02_Application/src/accounts-db/. --tag anthosequipofive1.azurecr.io/accounts-db:latest
           docker push anthosequipofive1.azurecr.io/accounts-db:latest

    - name: Build the Docker balancereader
      run: |
           docker pull gcr.io/bank-of-anthos/balancereader:latest
           docker tag gcr.io/bank-of-anthos/balancereader:latest anthosequipofive1.azurecr.io/balancereader:latest
           docker push anthosequipofive1.azurecr.io/balancereader:latest


    - name: Build the Docker contacts
      run: |
           docker build 02_Application/src/contacts/. --tag anthosequipofive1.azurecr.io/contacts:latest
           docker push anthosequipofive1.azurecr.io/contacts:latest

    - name: Build the Docker frontend
      run: |
           docker build 02_Application/src/frontend/. --tag anthosequipofive1.azurecr.io/frontend:latest
           docker push anthosequipofive1.azurecr.io/frontend:latest

    - name: Build the Docker ledger-db
      run: |
           docker build 02_Application/src/ledger-db/. --tag anthosequipofive1.azurecr.io/ledger-db:latest
           docker push anthosequipofive1.azurecr.io/ledger-db:latest
    
    - name: Build the Docker ledgerwriter
      run: |
           docker pull gcr.io/bank-of-anthos/ledgerwriter:latest
           docker tag gcr.io/bank-of-anthos/ledgerwriter:latest anthosequipofive1.azurecr.io/ledgerwriter:latest
           docker push anthosequipofive1.azurecr.io/ledgerwriter:latest    

    - name: Build the Docker loadgenerator
      run: |
           docker build 02_Application/src/loadgenerator/. --tag anthosequipofive1.azurecr.io/loadgenerator:latest
           docker push anthosequipofive1.azurecr.io/loadgenerator:latest

    - name: Build the Docker transactionhistory
      run: |
           docker pull gcr.io/bank-of-anthos/transactionhistory:latest
           docker tag gcr.io/bank-of-anthos/transactionhistory:latest anthosequipofive1.azurecr.io/transactionhistory:latest
           docker push anthosequipofive1.azurecr.io/transactionhistory:latest 

    - name: Build the Docker userservice
      run: |
           docker build 02_Application/src/userservice/. --tag anthosequipofive1.azurecr.io/userservice:latest
           docker push anthosequipofive1.azurecr.io/userservice:latest