name: Init Testing

on: 
  workflow_run:
    workflows: ["Init all Microservices Images"]
    types:
      - completed
  pull_request:
    branches: [ master ]
    types: [ closed ]
    paths: 
      - "02_Application/test/*"  
  

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v2

    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
