name: Init Services

on: 
  workflow_run:
    workflows: ["Init all Microservices Images"]
    branches: [master]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
