name: Init VM Vault

on: 
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TF_VAR_SSH_KEY: ${{secrets.SSH_PRIVATE_KEY_VM}}

    steps:
    - uses: actions/checkout@v2

    - name: Installing Ansible
      run: |
        sudo apt-get update -y
        sudo apt-get install ansible -y

    - name: Saving SSH
      run: |
          cd 05_Ansible/
          echo ${{env.TF_VAR_SSH_KEY}} > id_rsa 

    - name: Run playbook
      run: |
          cd 05_Ansible/
          ansible-playbook playbook.yaml -i inventory -u azureuser  --private-key id_rsa
    
    - name: Saving Tokens
      run: |
          cd 05_Ansible/rootKey
          cat rootkey

    - name: Saving UnsealKeys
      run: |
          cd 05_Ansible/unsealKey
          cat unseal_key_0
          cat unseal_key_1
          cat unseal_key_2
          cat unseal_key_3
          cat unseal_key_4
