name: Init VM Vault

on: 
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing Ansible
      run: |
        sudo apt-get update -y
        sudo apt-get install ansible -y

    - name: Saving SSH
      env:
        gpg_key: ${{secrets.GPG_PASS}}
      run: |
          cd 05_Ansible/
          gpg --quiet --batch --yes --decrypt --passphrase="$gpg_key" --output id_rsa private.key.gpg
          sudo chmod 600 id_rsa
          cat id_rsa 



