name: Init VM Vault

on: 
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.TF_VAR_SSH_KEY}}

    steps:
    - uses: actions/checkout@v2

    - name: Installing Ansible
      run: |
        sudo apt-get update -y
        sudo apt-get install ansible -y

    - name: Run playbook
      run: |
          cd 05_Ansible/
          ansible-playbook playbook.yaml -i inventory -u azureuser  
      
