name: Init VM Vault

on: 
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run playbook
    uses: dawidd6/action-ansible-playbook@v2
    with:
      # Required, playbook filepath
      playbook: playbook.yml
      # Optional, directory where playbooks live
      directory: 05_Ansible/.
      # Optional, SSH private key
      key: ${{secrets.TF_VAR_SSH_KEY}}
      # Optional, literal inventory file contents
      inventory: |
        [all]
        20.121.23.14
      # Optional, additional flags to pass to ansible-playbook
      options: |
        -u azureuser
      
