name: Init VM Vault

on: 
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing Ansible
      run: |
        sudo apt-get update -y
        sudo apt-get install ansible -y

    - name: Saving SSH
      env:
        TF_VAR_SSH_KEY: ${{secret.SSH_PRIVATE_KEY_VM}}
      run: |
          cd 05_Ansible/
          echo $TF_VAR_SSH_KEY > ~/.ssh/id_rsa 
          sudo chmod 600 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa



