name: Adservice Image 

on:

  push:
    branches: [ master ]
    paths: 
      - "02_Application/src/adservice/*"
  pull_request:
    branches: [ master ]
    paths: 
      - "02_Application/src/adservice/*"

jobs:

  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: Login Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}
        
    - name: Login Azure ACR
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}
    
    - name: Deleted Img in ACR
      run: |
          az acr repository delete --name hipsterequipofive1 --image ${{ secrets.ACR_SERVER }}/adservice:v1

    - name: Build the Docker images
      run: |
           docker build 02_Application/src/adservice/. --tag ${{ secrets.ACR_SERVER }}/adservice:latest
           docker push ${{ secrets.ACR_SERVER }}/adservice:latest
          
      
