name: Checkout service

on:
  push:
    branches: [ master ]
    paths: 
    - "02_Application/src/checkoutservice/*"
  pull_request:
    branches: [ master ]
    paths: 
    - "02_Application/src/checkoutservice/*"
    
jobs:
  
  build:
    
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: "Login Azure ClI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}
        
    - name: 'Login Azure ACR'
    - uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.ACR_SERVER }} # default: index.docker.io
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}
    
    - name: Build the Docker images
      run: |
           docker build src/checkoutservice/. --tag ${{ secrets.ACR_SERVER }}/checkoutservice:v1
           docker push ${{ secrets.ACR_SERVER }}/checkoutservice:v1
          
      
