name: paymentservice Chart 

on:
  workflow_run:
    workflows: ["Paymentservice Image"]
    types:
      - completed
  push:
    branches: [ master ]
    paths: 
      - "03_Helm_Charts/templates/paymentservice.yaml"

jobs:

  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: "Login Azure ClI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}

    - name: "Login AKS"
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }} # Azure credentials
        resource-group: 'rg-hipster-dev-eastus'
        cluster-name: 'aks-hipster-dev-eastus'
      id: login   
    
    - name: 'Install helm'
      uses: azure/setup-helm@v1
      with:
        version: latest # default is latest stable

    - name: Install Kubectl 
      uses: azure/setup-kubectl@v1  
      with:
        version: latest # default is latest stable
      id: install

    - name: Update New paymentservice
      run: |
           kubectl set image deployment/paymentservice server=${{ secrets.ACR_SERVER }}/paymentservice:latest 
          
      
