name: product catalog service 

on:
  push:
    branches: [ master ]
    paths: 
      - "02_Application/src/productcatalogservice/*"
  pull_request:
    branches: [ master ]
    paths: 
      - "02_Application/src/productcatalogservice/*"

jobs:

  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: "Login Azure ClI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}
        
    - name: 'Login Azure ACR'
    - uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.ACR_SERVER }} # default: index.docker.io
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}
    
    - name: Build the Docker images
      run: |
           docker build 02_Application/src/productcatalogservice/. --tag ${{ secrets.ACR_SERVER }}/productcatalogservice:v1
           docker push ${{ secrets.ACR_SERVER }}/productcatalogservice:v1
          
      
