name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths: 
      - "src/recommendationservice/*"
  pull_request:
    branches: [ master ]
    paths: 
      - "src/recommendationservice/*"

jobs:

  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
          login-server: hipsterequipofive1.azurecr.io # default: index.docker.io
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}
    
    - name: Build the Docker images
      run: |
           docker build src/recommendationservice/. --tag hipsterequipofive1.azurecr.io/recommendationservice:v1
           docker push hipsterequipofive1.azurecr.io/recommendationservice:v1
          
      
